# Generated by Django 4.2 on 2025-10-12 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('solvabilite_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compagnie',
            options={'ordering': ['nom'], 'verbose_name': "Compagnie d'assurance", 'verbose_name_plural': "Compagnies d'assurance"},
        ),
        migrations.AddField(
            model_name='compagnie',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='compagnie',
            name='adresse',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='compagnie',
            name='agrement_acpr',
            field=models.CharField(blank=True, max_length=50, verbose_name="Numéro d'agrément ACPR"),
        ),
        migrations.AddField(
            model_name='compagnie',
            name='date_agrement',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'agrément"),
        ),
        migrations.AddField(
            model_name='compagnie',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compagnie',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='compagnie',
            name='groupe',
            field=models.CharField(blank=True, max_length=200, verbose_name="Groupe d'appartenance"),
        ),
        migrations.AddField(
            model_name='compagnie',
            name='pays',
            field=models.CharField(default='France', max_length=100),
        ),
        migrations.AddField(
            model_name='compagnie',
            name='statut_reglementaire',
            field=models.CharField(choices=[('AUTORISEE', 'Autorisée'), ('SURVEILLANCE', 'Sous surveillance renforcée'), ('SUSPENDUE', 'Activité suspendue'), ('RETRAIT', "Retrait d'agrément")], default='AUTORISEE', max_length=50),
        ),
        migrations.AddField(
            model_name='compagnie',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='compagnie',
            name='type_compagnie',
            field=models.CharField(choices=[('ASSURANCE_VIE', 'Assurance Vie'), ('ASSURANCE_NON_VIE', 'Assurance Non-Vie'), ('ASSURANCE_MIXTE', 'Assurance Mixte'), ('REASSUREUR', 'Réassureur'), ('INSTITUTION_FINANCIERE', 'Institution Financière')], default='ASSURANCE_VIE', max_length=50),
        ),
    ]
