# Generated by Django 4.2 on 2025-10-13 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solvabilite_app', '0002_alter_compagnie_options_compagnie_actif_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donneessolvabilite',
            options={'ordering': ['-date_reference'], 'verbose_name': 'Données de Solvabilité', 'verbose_name_plural': 'Données de Solvabilité'},
        ),
        migrations.AddField(
            model_name='donneessolvabilite',
            name='catastrophes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='donneessolvabilite',
            name='charges_sinistres',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='donneessolvabilite',
            name='concentration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='donneessolvabilite',
            name='details_risques',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='donneessolvabilite',
            name='immobilisations',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='donneessolvabilite',
            name='longevite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='donneessolvabilite',
            name='mortalite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='donneessolvabilite',
            name='placements',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='donneessolvabilite',
            name='rachat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='donneessolvabilite',
            name='risque_actions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='donneessolvabilite',
            name='risque_contrepartie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='donneessolvabilite',
            name='risque_immobilier',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='donneessolvabilite',
            name='risque_primes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='donneessolvabilite',
            name='risque_sinistres',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='donneessolvabilite',
            name='risque_spread',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='donneessolvabilite',
            name='risque_taux',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='donneessolvabilite',
            name='fonds_propres',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='donneessolvabilite',
            name='passif_technique',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='donneessolvabilite',
            name='prime_annuelle',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='compagnie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solvabilite_app.compagnie'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ACTUAIRE', 'Actuaire'), ('RISK_MANAGER', 'Risk Manager'), ('CONTROLEUR', 'Contrôleur de Gestion'), ('DG', 'Directeur Général'), ('ADMIN', 'Administrateur'), ('REGULATEUR', 'Régulateur'), ('CLIENT', 'Client'), ('RH', 'Responsable RH')], default='CLIENT', max_length=20),
        ),
    ]
